-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create profiles table (extends auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  role text check (role in ('owner', 'employee')),
  business_id uuid, -- Will be a foreign key to businesses
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Create businesses table
create table public.businesses (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  owner_id uuid references public.profiles(id) not null,
  invite_code text unique not null,
  created_at timestamptz default now()
);

-- Add foreign key to profiles for business_id
alter table public.profiles
add constraint profiles_business_id_fkey
foreign key (business_id) references public.businesses(id);

-- Create timesheets table
create table public.timesheets (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) not null,
  business_id uuid references public.businesses(id) not null,
  clock_in timestamptz default now(),
  clock_out timestamptz,
  status text check (status in ('active', 'completed')) default 'active',
  created_at timestamptz default now()
);

-- Create locations table
create table public.locations (
  id bigint generated by default as identity primary key,
  timesheet_id uuid references public.timesheets(id) not null,
  user_id uuid references public.profiles(id) not null,
  lat double precision not null,
  lng double precision not null,
  timestamp timestamptz default now()
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.businesses enable row level security;
alter table public.timesheets enable row level security;
alter table public.locations enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone"
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile"
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile"
  on public.profiles for update
  using ( auth.uid() = id );

-- Policies for businesses
create policy "Businesses are viewable by members"
  on public.businesses for select
  using ( 
    auth.uid() = owner_id or 
    exists (select 1 from public.profiles where id = auth.uid() and business_id = public.businesses.id)
  );

create policy "Owners can insert businesses"
  on public.businesses for insert
  with check ( auth.uid() = owner_id );

-- Policies for timesheets
create policy "Employees can view their own timesheets"
  on public.timesheets for select
  using ( auth.uid() = user_id );

create policy "Owners can view their business timesheets"
  on public.timesheets for select
  using ( 
    exists (select 1 from public.businesses where id = public.timesheets.business_id and owner_id = auth.uid())
  );

create policy "Employees can insert timesheets"
  on public.timesheets for insert
  with check ( auth.uid() = user_id );

create policy "Employees can update their own timesheets"
  on public.timesheets for update
  using ( auth.uid() = user_id );

-- Policies for locations
create policy "Employees can insert locations"
  on public.locations for insert
  with check ( auth.uid() = user_id );

create policy "Owners can view locations for their business"
  on public.locations for select
  using (
    exists (
      select 1 from public.timesheets 
      join public.businesses on public.timesheets.business_id = public.businesses.id
      where public.locations.timesheet_id = public.timesheets.id 
      and public.businesses.owner_id = auth.uid()
    )
  );

-- Enable Realtime
alter publication supabase_realtime add table public.locations;
alter publication supabase_realtime add table public.timesheets;

-- RPC to get business ID by invite code (securely)
create or replace function get_business_id_by_invite(code text)
returns uuid
language plpgsql
security definer
as $$
declare
  bus_id uuid;
begin
  select id into bus_id from public.businesses where invite_code = code;
  return bus_id;
end;
$$;
